services:
  backend:
    build: ../server
    deploy:
      replicas: 4
    networks:
      - loadbalancing

  nginx:
    build: ../nginx
    container_name: nginx
    ports:
      - "3000:80"
    networks:
      - loadbalancing
    depends_on:
      - backend

networks:
  loadbalancing:
